### ISSUE TITLE
Projet  toujours d'actualité ?

### ISSUE THREAD

**Issue by b1nj** [xmaximin/SargaWatch#1]
Bonjour, ce projet est toujours d'actualité ?
Je voulais faire quelques chose de similaire pour mon site http://www.plages.mq/

**Comment by xmaximin** [comment]
J'ai repris le développement il y a une semaine. J'ai un projet urgent à sortir avant le 15. Après je vais surement reprendre Sargawatch. Et surement ouvrir le projet en Open Source d'ailleurs.

**Comment by b1nj** [comment]
Ok je vais suivre ton projet. C'est avec plaisir que je t'aurai donné un coup de main, mais je ne code pas en Java.

**Comment by xmaximin** [comment]
Ah dommage mais ce n'est pas grave, ça ira je  pense.
